### ISSUE TITLE
Failure to build missing frag_ao.cginc shader helper

### ISSUE THREAD

**Issue by warp** [spatialos/HelloWorld#4]
Building with Unity 5.5.0f3
```
Shader error in 'Hidden/SSAO': failed to open source file: 'frag_ao.cginc' at line 40
```
Resolved locally by copying `https://github.com/leapmotion/unity/blob/master/v1/leapdj/Assets/Standard%20Assets/Image%20Effects%20(Pro%20Only)/_Sources/Shaders/frag_ao.cginc` to `workers/unity/Assets/Standard\ Assets/Effects/ImageEffects/Shaders/` perhaps this file is no longer included with unity

**Comment by VegaDesert** [comment]
Downgrade to 5.4.x

**Comment by callum-improbable** [comment]
We're working on 5.5 support as we speak!
5.4.2 is the supported version for the platform!
Cheers!

**Comment by johnprobable** [comment]
Should be fixed now after the update to SpatialOS version 9.1.0.
